### ISSUE TITLE
add more intensity control

### ISSUE THREAD

**Issue by jxchen01** [MMV-Lab/3D-Cell-Viewer#27]
<img width="516" alt="Screenshot 2024-11-26 at 08 47 09" src="https://github.com/user-attachments/assets/54218482-2c71-4eb3-a46e-0d8169909a51">
Currently, under Channel, there are Auto IJ, Min/Max, Best Fit, 50-98% (By the way, you can call it Auto_98, 50-98% could be misleading). Can we add manual control like the histogram in the "Volume Setting" in the allen cell viewer?

**Comment by jxchen01** [comment]
<img width="357" alt="Screenshot 2024-12-01 at 21 08 37" src="https://github.com/user-attachments/assets/8854d65b-76b9-45a9-a2ce-0f8d6f857f15">
there are a few display issues: the two text fields are not aligned due to different text length. the Y-aixs of the histogram should be "Probability", not "opacity", correct? Also, the y-axis text is blocked by the numbers.

@Adrian-Sebuliba

**Comment by Adrian-Sebuliba** [comment]
> <img alt="Screenshot 2024-12-01 at 21 08 37" width="357" src="https://private-user-images.githubusercontent.com/7811075/391360098-8854d65b-76b9-45a9-a2ce-0f8d6f857f15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNDA4NjksIm5iZiI6MTczMzE0MDU2OSwicGF0aCI6Ii83ODExMDc1LzM5MTM2MDA5OC04ODU0ZDY1Yi03NmI5LTQ1YTktYTJjZS0wZjhkNmY4NTdmMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDJUMTE1NjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTM4MDlmZmJlNDdjYjYxYmRlOWQwZTgyOWQxNzIyMTZiYTYyMTJjNjRlYzkyYzkxMGQ5YjBlOTliYTQzZThkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.97GrHGP3z4aZkDEzT7roCFtFqjpbggdVZxdmy1cysOo"> there are a few display issues: the two text fields are not aligned due to different text length. the Y-aixs of the histogram should be "Probability", not "opacity", correct? Also, the y-axis text is blocked by the numbers.
> @Adrian-Sebuliba

@jxchen01 Thanks for your detailed feedback! Let me address each point:

1. Text field alignment: ✓
The styling has been fixed to ensure proper alignment of the intensity input fields regardless of text length. This improvement is now implemented in the latest version.

2. Y-axis label "Opacity" vs "Probability": 
Actually, "Opacity" is the correct label for the main y-axis in this context. Here's why:
- The transfer function curve represents a direct mapping from voxel values (x-axis) to opacity/visibility levels (y-axis)
- This is a deterministic transformation function rather than a probability distribution
- The values are used directly for rendering: 0 = fully transparent, 1 = fully opaque
- Users are explicitly controlling visibility levels, not probabilities

The background histogram does show a frequency distribution of voxel values, and we could potentially add a secondary y-axis for this if helpful. However, the primary y-axis should remain "Opacity" as it reflects the actual transformation being applied.

3. Y-axis label overlap: ✓
The spacing has been adjusted to prevent the y-axis label from being blocked by the axis values. We've increased the left margin and optimized the positioning of both the label and tick values.

Let me know if you'd like to see any further adjustments to these improvements.

**Comment by Adrian-Sebuliba** [comment]
I was thinking about changing  "Intensity" to "Voxel Value" - it's more technically accurate and helps users understand they're mapping raw data values to visibility levels. Each voxel in the 3D volume has a specific value, and the transfer function determines how visible that voxel will be in the final rendering, What do you think @jxchen01 ?

**Comment by jxchen01** [comment]
<img width="357" alt="Screenshot 2024-12-02 at 14 20 52" src="https://github.com/user-attachments/assets/98c76913-59e4-4778-8e2c-52283bb740bc">
the display is better, but still not ideal. the min and max are not centered, while there is a big blank area between the histgram and the min / max text fields ... this part needs a little more polish.
